activation:
  quantized_relu(2,2): 2
  quantized_relu(3,3): 3
  quantized_relu(4,4): 4
  quantized_relu(5,5): 5
  quantized_relu(6,6): 6
  quantized_relu(7,7): 7
  quantized_relu(8,8): 8
bias:
  quantized_bits(2,0,alpha=1.0): 2
  quantized_bits(3,0,alpha=1.0): 3
  quantized_bits(4,0,alpha=1.0): 4
  quantized_bits(5,0,alpha=1.0): 5
  quantized_bits(6,0,alpha=1.0): 6
  quantized_bits(7,0,alpha=1.0): 7
  quantized_bits(8,0,alpha=1.0): 8
kernel:
  quantized_bits(2,0,alpha=1.0): 2
  quantized_bits(3,0,alpha=1.0): 3
  quantized_bits(4,0,alpha=1.0): 4
  quantized_bits(5,0,alpha=1.0): 5
  quantized_bits(6,0,alpha=1.0): 6
  quantized_bits(7,0,alpha=1.0): 7
  quantized_bits(8,0,alpha=1.0): 8